from musicxml import *

print("// generated by python.")
print('#include "musicxml.h"')

print("")
print('const MusicxmlKeywords musicxml = {')

for e in elements:
    e_str = to_c_ident(e)

    if is_in_parser_c(e_str):
        print(f'    .{e_str} = STR_REF("{to_c_str_ref(e)}"),')

print('};')


print('const char* musicxml_chords[] = {')
for v in chords.values():
    print(f'    "{v}",')
print('};')
